data<-read.table("household_power_consumption.txt", na.string="?",sep=";",header=TRUE)
data1<-subset(data,Date=="1/2/2007")
data2<-subset(data,Date=="2/2/2007")
data3<-rbind(data1,data2)
data3$Date<-as.Date(data3$Date, format="%d/%m/%Y")
data3Time<-strptime(str(data3$Time[1]), format="%d/%m/%Y %H:%M:%S")
png("plot4.png")
par(mfrow=c(2,2))
plot(strptime(paste(data3$Date,data3$Time), format="%Y-%m-%d %H:%M:%S"),data3$Global_active_power, type="l",xlab="",ylab="Global Active Power (kilowatts)")
plot(strptime(paste(data3$Date,data3$Time), format="%Y-%m-%d %H:%M:%S"),data3$Voltage, type="l",xlab="datetime",ylab="Voltage")
plot(strptime(paste(data3$Date,data3$Time), format="%Y-%m-%d %H:%M:%S"),data3$Sub_metering_1, type="l",xlab="",ylab="Energy sub metering")
lines(strptime(paste(data3$Date,data3$Time), format="%Y-%m-%d %H:%M:%S"),data3$Sub_metering_2, xlab="",ylab="Energy sub metering",col="red")
lines(strptime(paste(data3$Date,data3$Time), format="%Y-%m-%d %H:%M:%S"),data3$Sub_metering_3, type="l",xlab="",ylab="Energy sub metering",col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black","red","blue"))
plot(strptime(paste(data3$Date,data3$Time), format="%Y-%m-%d %H:%M:%S"),data3$Global_reactive_power, type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()
