data<-read.table("household_power_consumption.txt", na.string="?",sep=";",header=TRUE)
data1<-subset(data,Date=="1/2/2007")
data2<-subset(data,Date=="2/2/2007")
data3<-rbind(data1,data2)
data3$Date<-as.Date(data3$Date, format="%d/%m/%Y")
data3Time<-strptime(str(data3$Time[1]), format="%d/%m/%Y %H:%M:%S")
png("plot2.png")
plot(strptime(paste(data3$Date,data3$Time), format="%Y-%m-%d %H:%M:%S"),data3$Global_active_power, type="l",xlab="",ylab="Global Active Power (kilowatts)")
dev.off()